# https://github.com/docker-library/docs/blob/master/postgres/README.md#-via-docker-compose

name: kanban-api

services:

  db:
    image: postgres:16-alpine
    container_name: kanban-db
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER_NAME} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: kanban-db-admin
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      db:
        condition: service_healthy

  app:
    build: .
    container_name: kanban-api
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER_NAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_USER_PASSWORD}
      SPRING_FLYWAY_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_FLYWAY_USER: ${DB_USER_NAME}
      SPRING_FLYWAY_PASSWORD: ${DB_USER_PASSWORD}
      SPRING_SECURITY_JWT_EXPIRATION: ${SECURITY_JWT_EXPIRATION}
      SPRING_SECURITY_JWT_SECRET: ${SECURITY_JWT_SECRET}
      SPRING_SECURITY_USER_NAME: ${SECURITY_USER_NAME}
      SPRING_SECURITY_USER_PASSWORD: ${SECURITY_USER_PASSWORD}
      SPRING_ADMIN_USER_EMAIL: ${ADMIN_USER_EMAIL}
      SPRING_ADMIN_USER_FIRST_NAME: ${ADMIN_USER_FIRST_NAME}
      SPRING_ADMIN_USER_LAST_NAME: ${ADMIN_USER_LAST_NAME}
      SPRING_ADMIN_USER_PASSWORD: ${ADMIN_USER_PASSWORD}

volumes:
  postgres_data: