spring.application.name=kanban-api
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/db_kanban
spring.datasource.username=db_user
spring.datasource.password=db_pwd_changemeinprod
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
